name: "Feature Request"
description: Create a new ticket for a new feature request 
title: "[FEAT]: "
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Detailed Description"
      description: Provide a detailed explanation of the feature
      placeholder: Describe in detail your feature request
    validations:
      required: false
